# Set variables for execution.
# Make sure your credentials are correct.
# Make sure ACP and all logging and inspection objects already exist.
loglevel: DEBUG
device: 10.10.10.100
username: api-user
password: api-password
domain: Global
ac_policy: api-test-policy

# Inspection settings
# Leave variable empty (var: ') if you don't want to include the setting
intrusion_policy: api-intrusion-policy
file_policy: api-file-policy
variable_set: api-variable-set

# Logging settings
#  Leave variable empty (var: '') if you don't want to include the setting
syslog_to_server: api-syslog-server

# these are boolean, just use true/false
log_to_fmc: true
log_at_begin: false
log_at_end: true